feat(deps): updates and adds support for rollup v3
brodybits/rollup-plugin-size-snapshot pull request #25
Opened 2023-08-23 16:21 UTC by geotrev

I think this should be a somewhat simple PR but let me know if there are additional things I should test for... the existing plugins seem to hold up.

Addresses #24

2023-08-30 00:55 UTC, brodybits requested changes
My apologies for the delay, I think we need to add CI testing with Rollup v2 as well.

Maybe the best thing would be to check the output sizes less precisely with Rollup v2. To do this in CI, I would recommend an approach like this:

- add CI task that adds specific npm or Yarn installation of Rollup v2, test with an environmental variable defined if using Rollup v2
- then test some sizes less precisely or consider other adjustments in case of Rollup v2

As an alternative: we *could* also drop support for Rollup v2 in a new 0.x release of this Rollup plugin. I think this could be an acceptable alternative if we document it somewhere as this fork does not seem to have too many users.

Thanks for your contribution, definitely much appreciated!

2023-08-30 01:11 UTC, geotrev commented
@brodybits thanks for taking a look! 

Do you anticipate new/changing features that would make backwards compatibility on Rollup v2 beneficial? If not, bumping to a new minor and dropping v2 support works for me. In that case, I can update the README.

Give it some thought, I'm cool making changes in either direction. 👍🏻

2023-08-30 12:21 UTC, brodybits commented
My first choice would be to support both Rollup v2 & v3 with testing, raised #26 to track this.

I can merge this PR for a new minor release if we remove the Rollup v2 option, and resolve #26 whenever someone has time to work on this.

Thanks!

2023-09-04 15:24 UTC, brodybits commented on package.json
> +    "rollup": "^2.0.0 || ^3.0.0"
I would like to drop rollup v2 support for now.

At this point test suite works with more recent rollup v2 such as 2.40 & 2.79.1 but not all the way back to `2.0.0`. And the proposed updates will succeed with Rollup pre-release `4.0.0-13`. So I would likely favor moving forward supporting the newer Node.js versions.

```suggestion
    "rollup": "^3.0.0"
```

2023-09-04 15:36 UTC, geotrev commented
Sounds good, thanks.

2023-09-04 15:40 UTC, brodybits approved these changes
Approved & merging with removal of Rollup v2 support, as already discussed, thanks!

2023-09-04 15:44 UTC, merged